package com.example.designreco.domain;

import java.time.LocalDateTime;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * 디자인 템플릿/에셋 메타데이터.
 * R2DBC 엔티티는 JPA와 달리 연관관계 매핑을 지원하지 않음 — 다국어 텍스트는
 * {@link AssetTranslation}에 asset_id로만 연결해두고, 조회 시 서비스 레이어에서
 * reactive flatMap으로 직접 조립함.
 */
@Getter
// R2DBC도 JPA처럼 매핑 프레임워크가 리플렉션으로 값을 채워 넣을 기본 생성자, 그리고
// DummyDataInitializer 등에서 새 레코드를 만들 때 쓸 전체 필드 생성자가 필요해서 Lombok으로 둘 다 생성.
@NoArgsConstructor
@AllArgsConstructor
@Table("asset") // 이 클래스가 매핑되는 테이블 이름. JPA의 @Entity+@Table과 달리 R2DBC는 @Table 하나로 끝.
public class Asset {

	@Id // PK. asset 테이블은 GENERATED BY DEFAULT AS IDENTITY라 insert 시 null로 넘기면 DB가 채워줌.
	private Long id;

	private String category;

	// ponytail: pgvector 대신 double 배열 + 애플리케이션 레벨 코사인 유사도로 시작.
	// 카탈로그 규모가 커져서 전수 스캔이 느려지면 pgvector 확장 + vector 컬럼으로 교체.
	// double이 아니라 Double(박싱된 래퍼)인 이유: R2DBC postgres 드라이버가 SQL 배열 타입을
	// 매핑할 때 참조 타입 배열(Double[])을 기대함 — 기본형 배열(double[])은 매핑이 안 됨.
	private Double[] embedding;

	private LocalDateTime createdAt;
}
