-- 참고용 DDL. 앱이 자동 실행하지 않음 — 로컬 PostgreSQL에 수동으로 적용할 것.
-- psql -h localhost -U <계정> -d design_reco -f schema.sql

create table asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category varchar(30) not null,
    -- ponytail: pgvector 확장 대신 double precision[] + 애플리케이션 레벨 코사인 유사도로 시작.
    -- 카탈로그가 커져서 인덱스 없는 전수 스캔이 느려지면 pgvector 확장 설치 후 vector 타입 + <=> 연산자로 교체.
    embedding double precision[] not null,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

create table asset_translation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL REFERENCES asset (id),
    locale varchar(5) not null,
    title varchar(100) not null,
    description varchar(500),
    unique (asset_id, locale)
);

create table user_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL REFERENCES asset (id),
    event_type varchar(20) not null, -- VIEW / USE
    created_at TIMESTAMP NOT NULL DEFAULT now()
);
