-- 참고용 DDL. 앱이 자동 실행하지 않음 — 로컬 PostgreSQL에 수동으로 적용할 것.
-- psql -h localhost -U <계정> -d backend_prep -f schema.sql

create table member (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(20) not null,
    email varchar(50),
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    update_at timestamp
);

create table document(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(50),
    content varchar(4000),
    owner_id INT REFERENCES member (id),
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    update_at timestamp
);

-- 04번 문서 Part C(인덱스 유무 비교) 실습에서 추가한 인덱스
create index idx_document_owner_created on document(owner_id, created_at desc);
